### ISSUE TITLE
Not all genes from 1K CosMx in references?

### ISSUE THREAD

**Issue by roanvanscheppingen** [Nanostring-Biostats/CosMx-Cell-Profiles#2]
Given the mouse dataset and a user-generated Cosmx seurat I run Insitutype. 
My expression matrix has a length of 1000 (genes)

Your references have a length of 950 (genes).

The following genes in the count data are missing from fixed_profiles and will be omitted from clustering: Abl2,Acaca,Adcy5,Atg10,Bmpr1b,Cdc14b,Cplx1,Csmd3,Ddt,Dnah6,Dync1i1,Dynll1,Entpd2,Fnip2,Icmt,Lama2,Lgi2,Lrrc4c,Maml3,Masp1,Neo1,Neu4,Pde1c,Pde7b,Pgls,Phactr1,Pias1,Pik3c3,Pla2g4c,Plcl1,Pmch,Prps2,Ptprj,Rspo2,Sh3gl3,Slc24a3,Slc39a10,Snhg11,Sos2,Sstr3,Tab2,Tacr3,Thsd4,Tspan3,Ulk2,Unc5d,Uqcrq,Usp34,Vav3,Zfyve9

Why are these genes not in the profiles?
And given that they are not exactly the same (something eluded to in the readme), should the reference profile then be updated for use in InSituType?

**Comment by acjordan333** [comment]
Hi Nanostring team, 

I have the same question. Will the reference matrices be updated? Also, will there be a new set of matrices created using the CosMx 6,000 plex assay? Will the 6,000-plex assay allow for the identification of more granular cell types (CD4 naive vs CD4 memory, for example)? Thanks for looking into this in advance.
