### ISSUE TITLE
Mouse Pancreas Profile

### ISSUE THREAD

**Issue by acjordan333** [Nanostring-Biostats/CosMx-Cell-Profiles#3]
Hi team, 

Are there any plans to create a mouse benign pancreas or malignant pancreas profile that can be used for any cosmx experiments run on pancreas cancer mouse models?

Best,
Alex

**Comment by mgrout81** [comment]
Hello Alex,

Thanks for your interest. No, there are no upcoming plans for non-brain mouse organs. The only CosMx product available for mouse is a neuroscience panel.

**Comment by mgrout81** [comment]
Apologies for the error. There are no current plans to release mouse pancreas reference profiles internally, although we do hope to open this resource to user submissions in the future. The analysis recommendation for mouse pancreas at this time would be to perform unsupervised clustering, and then classify immune cell types using a reference such as one provided here (snRNAseq-based): https://github.com/Nanostring-Biostats/CellProfileLibrary/tree/master/Mouse/Adult.

**Comment by acjordan333** [comment]
Ok sounds good. I have tried this as well. It seems that fully unsupervised clustering on mouse pancreas data seems to work OK for now.
